### ISSUE TITLE
[Feature Request] Left-align compendium titles

### ISSUE THREAD

**Issue by M0nk3yy** [phenomen/fvtt-custom-compendium-banners#1]
Hi Phenomen, thank you for this module. It is very much appreciated! I am enjoying being able to make the compendiums far more minimal.

![image](https://github.com/phenomen/fvtt-custom-compendium-banners/assets/66137312/f66ae5df-c47c-4a6a-925c-fa55829d0847)

My suggestion would be an option to left-align the compendium titles. I believe this is generally how text items in lists should be formatted for ease of reading so I hope you will consider it.

Thanks.

**Comment by Drakynn** [comment]
While left aligning, make sure there's a 12px indent to show the folder nesting heirachy.  If the indent is too small  (like V11 current 3px) it's very hard to see what's nested in what over the complete height of the list.

**Comment by phenomen** [comment]
@M0nk3yy thanks for suggestion! I added it in the update
![image](https://github.com/phenomen/fvtt-custom-compendium-banners/assets/138311/b075597c-23ef-4625-977c-8120194bcb97)

**Comment by M0nk3yy** [comment]
Thanks phenomen it looks great!

@Drakynn Adding the indent in the left-aligned text just means there is a gap:

![image](https://github.com/phenomen/fvtt-custom-compendium-banners/assets/66137312/e11c8f0d-4ad2-4e7f-a7e3-c216ab4bf51d)

Even with Mushies Subfolder Indent mod - the added indent just stacks on top of what the folder indent is

![image](https://github.com/phenomen/fvtt-custom-compendium-banners/assets/66137312/f2fe6267-bbf3-4840-a3ed-10e630fef410)

I think you were intending for this suggestion to replicate the Subfolder Indent mod but that is not what the text alignment indent does. I think this really just becomes wasted space.

**Comment by Drakynn** [comment]
I guess it's a matter of personal preference.  I don't find it wasted space if it adds clarity to the folder heirarchy.   I've just opted to make a tiny CSS change.   The default 3px indent is almost imperceptable on a 5K monitor.

**Comment by M0nk3yy** [comment]
The additional clarity is added by the increased folder indent, rather than the text indent. That's what the screenshot comparison shows. The first picture is left aligned with core indent. The second is left aligned with Mushies Subfolder Indent mod.
