### ISSUE TITLE
[Bug] Toggle Edit Lock and Configure Ownership buttons revert height and source settings

### ISSUE THREAD

**Issue by M0nk3yy** [phenomen/fvtt-custom-compendium-banners#2]
As soon as either the `Toggle Edit Lock` or `Configure Ownership` functions are used, the compendiums revert to default settings, losing the configured height and hidden source settings.

![image](https://github.com/phenomen/fvtt-custom-compendium-banners/assets/66137312/9c389948-d59f-4723-8cef-18ca84b904e6)

![image](https://github.com/phenomen/fvtt-custom-compendium-banners/assets/66137312/3460be84-af0e-45b5-bb32-d9e7c3f6e757)

![image](https://github.com/phenomen/fvtt-custom-compendium-banners/assets/66137312/a95a036a-d250-4a9e-9753-2e3da8dcc7a4)

My current settings when testing:

![image](https://github.com/phenomen/fvtt-custom-compendium-banners/assets/66137312/10cfb1c4-f126-411a-a7f5-22b6f0ac862a)

**Comment by Drakynn** [comment]
Sorting the folders alphabetically or altering the colour of one folder also causes the height and source settings to be ignored until you do a reload.
